
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Musikproduktion ApS','Sigurdsgade 39','2200','20461842');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Krabbenhøft +Ingolfsen','Thorsgade 59, 4 TV','2200','32105532');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Escobar ','Blågårdsgade 2A','2200','30226077');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Gaarden & Gaden ','Nørrebrogade 88','2200','55550880');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('20A ','Ravsborgade 20a','2200','25974601');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Ro Chokolade','Jægersborggade 25','2200','36966519');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Seven Eleven Nørrebro','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('VerdensKulturCentret','Nørre Allé 7','2200','2329 7906');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Sallings Optik','Nørrebrogade 118','2200','33370818');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Café Gavlen','Ryesgade 1','2200','35370237');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Gefärlich','Fælledvej 7','2200','35 24 13 24');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Knast','Stefansgade 3','2200','24460440');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Mondo Kaos','Birkegade 1','2200','60 95 11 36');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Whoppie','Fælledvej 15','2200','22 23 08 08');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Guld og Urt','Gartnergade 18 ','2200','27 62 83 00');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Tribeca NV ','','2400','35 85 10 50');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Hill Street','Blegdamsvej 30','2200','39 64 39 10');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Wix Wax','Rantzausgade 42','2200','51 91 40 29');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Insula Music','Blågårdsgade 31 th','2200','27 28 88 36');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Salon Jargon','Jægersborggade 58','2200','23 62 32 49');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Route 66','','2200','26 89 26 17');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('BG Shop','Åboulevard 32','2200',' 31 51 40 24');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Hellig Kors Kirke','Kapelvej 38','2200',' 35359822');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('GUL','Blågårdsgade 18','2200','25317545');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('www.ren-linne.com','Ravnsborggade 19, 2. th','2200','25568485');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Den Lille Billedskole' I Skrotlaboratoriet','Fensmarkgade 23 butik 2','2200','20 66 90 77');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Ravnsborg Vinbar','Ravnsborggade 19','2200','61 46 34 39');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Phenomenon ApS','Nørrebrogade 7 St th','2200','35 34 33 27');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Cafe Blågårds Apotek','Blågårdsgade 20','2200','35 37 24 42');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('TOURSINCOPENHAGEN','Struenseegade 38 4 th','2200','30 32 28 79');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Ali Bageri ApS','Heimdalsgade 39','2200','32 57 63 42');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Cafe Lækkerier','Vedbækgade 13','2200','53 66 39 74');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('The General Store','Ægirsgade 39','2200','28340081');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Social','Peblinge dossering 4, kld th','2200','25386012');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Hygge by Berlin','Jægersborggade 37','2200','26172618');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Depanneur','Griffenfeldtsgade 2','2200','28452127');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Guldblomst','Guldbergsgade 61','2200','29106661');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Vinskabet','Baggesensgade 9','2200','27424107');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Bau Bau','Birkegade 3','2200','40862937');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('ISTID','Jægersborggade 13','2200','61311834');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Café Griffens','Griffenfeldsgade 4C','2200','28387038');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('IBC Fysioterapi','Lygten 2c','2200','28724556');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Collective','Elmegade 21','2200','31324346');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Simeon-Sankt Johannes menighedsråd','Blegdamsvej 1A','2200','35 86 86 20');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Guldberg Slagter','Guldbergsgade 51A','','61 77 82 62  ');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Musiksmag','Jægersborgade 43','','60 19 14 94');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('KEA','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Relæ, Manfreds, Bæst, Mirabelle','Jægersborggade 40','2200','36 96 65 93');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Fitnesso Aps','Nørrebrogade 227','','+45 3110 7818');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Lygten / Pilegården','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Vi mødtes gennem ','Heimdalsgade 6A','','43 68 53 56');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Musik accord: Vinyl, CD, DVD, Blu-ray etc.../ Music & Movies. Vinyl, CD, DVD, Blu-ray...','Nørrebrogade','','70 15 16 17');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Ypga-cph','Peblinge Dosseringen 6','','40755502');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Ark books and Art Edition','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Bindia','Elmegade 6 ','','35378737');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Bisquitfabrikken','Jægersborggade 40','','40 16 04 91');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('tagtomat','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Temple bar','Nørrebrogade 48','','35 37 44 14');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('TO'SK','Jagtvej 131','','35 85 35 86');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Slagter Svendsen','Jagtvej 130','','26 28 06 62');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Terroristen ','Jægersborggade 52','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Teatergruppen Batida','Rentemestervej 25A','2400','3810 3609');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Tandori Masala','Nørrebrogade 35','','35353527');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Fri Bikeshop','Griffenfeldsgade 37','',' 35371571');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Loke cykler','Nørrebrogade 10 + 94','','35371591');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Golden Age','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Mr. Larkin ','Nørre Allé 1','','53773352');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Sexolog ','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Melange de Luxe','Ravnsborggade 6','','22 63 65 75');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Føtex','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Empire Bio','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('GAO dumpling Bar','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Say Concept Store','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('BlueTaco','Blågaardsgade 1','2200','32 20 80 00');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Tidens Mester','Birkegade 28','2200','22660966');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Keramiker Inge Vincents','Jægersborggade 27','2200','40701750');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Kingos Kirke','Bragesgade 35','2200','40 29 51 26');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Høj Copenhagen','Jægersborggade 53','2200','26135425');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Craving Aps ','Guldbergsgade 57','2200','30 22 57 93');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Design by Christensen ','Nørre Allé 15. A   ','2200','22 23 33 11 ');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Cafe Plenum ','Skt Hans Torv 2','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Nørrebro Teater','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Høkeren','Ravnsborggade 13','2200','35353244');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Sankt Stefans Kirken','Nørrebrogade 191','2200','21407005');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Kates Joint','Blågårdsgade 12','2200','35374496');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Karl Lund A/S','Ryesgade 19','2200','35 35 46 66');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Bethlehemskirken','Kapelvej 38','2200','35 39 77 03');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Hot Kotyr','Nørrebrogade 76','2200','35390274');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Nørrebro Teater','Ravnsborggade 3','2200','35 35 27 60');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Won Hundred','Guldbergsgade 29','2200','35343460');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Sneakers & Coffee','Jægersborggade 30','2200','42 57 67 89');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Hoha','Elmegade 14 & 20','2200','61336037');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Malbeck','Birkegade 2','2200','32 215 215');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Ladyfingers','Jægersborggade 4 ','','20 97 18 55');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('FEELGOOD BAKERY',' Prinsesse Charlottes Gade 4','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Nørrebro Bycenter','','','+45 27 90 14 69');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('KBH.HAUT','Ryesgade 1','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Koncertkirken Blågård','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Bevar's','Ravnsborggade 10B','','+45 5059 0993');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Bar Next Door, Alabama Social, Hanzo &  Gran torino','','','+45 31 35 36 32');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('advokat Dan Harild','Wesselsgade 17','','2943 3347');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('NOVA','','',' 4271 3626');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Uh la la Ceramics','Julie Bonde Bülck','','2674 7408');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('MOND','','','30 95 90 48');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('tabernacle twins','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Epoke rum','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Nørrebro City Cykler','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Elgiganten','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Nørrebro Lokaludvalg','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Nørrebro Bycenter','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Aveny','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Teatergrad','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Tøjeksperten','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Mr Graugaard','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Bager Munch','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Divan Kebab','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Mixit','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Brus/Spontan','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Pedal and company','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('California Kitchen','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Nørrebohallen ','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Siam DK','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('Zatar','','','');
INSERT INTO 'CA3DB'.'SHOP' ('NAME','ADDRESS','ZIP','PHONE') VALUES ('morten@nativenorth.dk','Elmegade 3','2200','42950800');